name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          npm install -g vsce
          vsce package
          vsce publish --pat ${{ secrets.DEVOPS_PAT }}
